# Generated by Django 5.0.3 on 2024-03-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_post_updated_at_customtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtoken",
            name="user",
        ),
    ]
